### ISSUE TITLE
Hotkeys not working

### ISSUE THREAD

**Issue by skarfie123** [joaomgcd/JoinDesktop#23] opened 2021-04-27 21:48 UTC
Only "Show App" hotkey is working. the three media hotkeys and any custom ones I add to device actions also don't work.

I am able to set the hotkey fine, just nothing happens when I try to use it.

I have tried simpler hotkeys too, in case these were too complex, but still no luck.

![image](https://user-images.githubusercontent.com/50425728/116316932-91f58e00-a7aa-11eb-89f1-a7287216a559.png)

**Comment by joaomgcd** [comment] 2021-04-28 07:37
Thanks for the report. I cannot reproduce...

Does the "Repeat Last Command" one also not work? Could you try with something like Shift + Control + L please?

**Comment by skarfie123** [comment] 2021-04-28 09:56
Just tried `Shift + Control + L` with "Repeat Last Command". Able to set it, but nothing happens when I press it.

**Comment by joaomgcd** [comment] 2021-04-29 14:17
Thanks. What OS are you on?

**Comment by skarfie123** [comment] 2021-04-29 15:00
Windows 10
Version 20H2
Build 19042.928

**Comment by joaomgcd** [comment] 2021-04-29 15:03
Thanks. Exactly the same as me so it can't be that. If you set shortcut you used for the Show App action on a different action, does that work? I'm thinking that some other app may be blocking these?

**Comment by skarfie123** [comment] 2021-04-29 15:24
Let ASC = Alt+Shift+Control
Ok, I Tried ASC + F1 And it worked for all cases.
Then I tried F2, F3 and they also worked.
However, as soon as I set one of them to ASC+Digit8 or ASC+Numpad8, they don't work but they also make the F one not work.

Minimal example:
Before:
Skip Song = ASC + F3 (Working)
After:
Skip Song = ASC + F3 (Not Working)
Show App = ASC + Digit8 (Not Working)

Much more complex than I expected...

**Comment by joaomgcd** [comment] 2021-04-29 16:31
So, just so I understand, if all your shortcuts are just based on Ctrl+Shift for example, it all works?

**Comment by skarfie123** [comment] 2021-04-29 16:58
It doesn't matter if its Alt+Ctrl+Shift or Ctrl+Shift.
Simply introducing a hotkey with Digit or Numpad, breaks any previously working ones with F
Eg.
If I only use F ones, it works. eg ASC+F1 and ASC+F2 both work
If I introduce a digit or Numpad one, neither ASC+F1 nor ASC+Digit1 work (ie the F1 hotkey stops working because of Digit1)

**Comment by joaomgcd** [comment] 2021-04-30 13:17
Ok, fixed on [this commit](https://github.com/joaomgcd/JoinDesktop/commit/a32b6792d6189748245eb36b37f37f26d90d58ed#diff-c4d13648415e98bd6e4bb60738cfd1ffc5384f567bdc9c5a22ca9c664222b72e)! :) Thank you!

**Closed by joaomgcd** 2021-04-30 13:17 UTC
