### ISSUE TITLE
Issue authenticating and connecting Join Desktop

### ISSUE THREAD

**Issue by profucius** [joaomgcd/JoinDesktop#1] opened 2020-07-10 13:45 UTC
I've downloaded the Join desktop app, and at first launch it asks to load a browser window to authenticate. 
![image](https://user-images.githubusercontent.com/18254607/87161754-f8003b80-c292-11ea-9328-d4c7775c6f57.png)

I do that, and login with my google account. It then shows a window with text saying it will load another window, it does that, and says authentication is complete and that I can close the window.

![image](https://user-images.githubusercontent.com/18254607/87161877-1fef9f00-c293-11ea-8500-f5bbfe9669bb.png)

However, the Desktop App is not showing anything; It is a plain white window with a spinning reload icon at the top right.

![image](https://user-images.githubusercontent.com/18254607/87161145-131e7b80-c292-11ea-90a0-568e8c60e184.png)

Also in the web browser tab, it shows this error. I've tried this with Chrome, Opera, and Firefox, same error.

![image](https://user-images.githubusercontent.com/18254607/87161132-0dc13100-c292-11ea-8394-3cbbff5665ac.png)

Then, I close and reopen the Desktop App, and it does show the tabs, but I'm seeing the error at the top like I did in the browser tab. I also do not see any of my devices, which I do have connected in the UWP app just fine.

![image](https://user-images.githubusercontent.com/18254607/87161291-537df980-c292-11ea-8809-86f8a22efdad.png)

UWP is fine:

![image](https://user-images.githubusercontent.com/18254607/87161332-6264ac00-c292-11ea-8182-378656ac0661.png)

**Comment by joaomgcd** [comment] 2020-07-10 18:06
Ok, the website has a bug right now that I'll try to fix ASAP. To work around it for now you should load the website on the devices tab and then press the refresh arrow at the top right of the join top par. After that's done refresh the page in Chrome. check if the errors go away that way. If they do, please go to settings and press the button to connect to the Desktop app again. Then just for good measure restart the desktop app. Does that make it work? :)

**Comment by yochananmarqos** [comment] 2020-07-10 19:36
What he described above is also happening. However, for me it opens the authentication tab in the background for a split second and closes. Then it's going in an endless loop. I'm already signed in via the Chrome extension.

I built the Linux application from source on Manjaro GNOME. My AUR package: [`joindesktop-git'](https://aur.archlinux.org/packages/joindesktop-git/).

**Comment by joaomgcd** [comment] 2020-07-13 10:58
Thanks for the report. Other people are having this issue as well. I'll try to fix it and get back to you. thanks for testing!

**Comment by yochananmarqos** [comment] 2020-07-13 15:19
With the latest commit I was able to get signed in and it's somewhat functional. Thanks!

**Comment by joaomgcd** [comment] 2020-07-13 15:27
Hi thanks for letting me know! :) Can you clarify why "somewhat functional"? What exactly is not working for you?

**Comment by yochananmarqos** [comment] 2020-07-13 15:37
Sorry, I wasn't clear. I meant it appeared to be functioning, but I hadn't had a chance to fiddle around with it yet. I'll let you know if I encounter any other issues. 

By the way, I added this to the AUR as [`joindesktop-git`](https://aur.archlinux.org/packages/joindesktop-git/).

**Comment by joaomgcd** [comment] 2020-07-14 09:28
> I've downloaded the Join desktop app, and at first launch it asks to load a browser window to authenticate....

Are you able to test this now? Is it still not working?

**Comment by Joecascio2000** [comment] 2020-07-16 01:22
I just tried setting up Join Desktop and it doesn't seem to be working but the issue is different than the two in this thread.
For me, Join Desktop says "Join will now sign you in via the Join website" then it successfully opens the website. The website displays "Must be registered. To make the desktop app work correctly your browser needs to be registered as a Join device." This is where it doesn't seem to be working. I'm not sure how to force it to register.

Using Edge Chromium browser: Version 83.0.478.64 (Official build) (64-bit)

**Comment by Itay-kun** [comment] 2020-07-16 20:23
On my end the test site doesn't get my browser as a registered join device so it doesn't complete the authentication

![image](https://user-images.githubusercontent.com/22597557/87718550-a6880d00-c7ba-11ea-9304-5300aad74f42.png)

also in the desktop app the consol shows user as null because of resources loading fail
![image](https://user-images.githubusercontent.com/22597557/87718902-4180e700-c7bb-11ea-98ad-9c0426d70890.png)

(i'm on windows 10, tested with Chrome and with Brave browsers)

**Comment by Joecascio2000** [comment] 2020-07-16 20:44
The screenshots that @Itay-kun provided match mine. I tried manually looking of the file and it appears that app.asar is a file and not a folder.
![image](https://user-images.githubusercontent.com/2560796/87720758-49646b00-c76a-11ea-9189-de992f9e5b24.png)

**Comment by joaomgcd** [comment] 2020-07-17 09:58
That "dexie" warning is really not an issue, just a warning. It won't stop anything from working.
It's normal that it wasn't able to load the user because you weren't signed in yet.

Could you please try going in http://testsjoaomgcd.appspot.com/ and the force-refreshing (Ctrl+F5) and see if that forces it to register itself as a device?
If that doesn't work could you please right-click the page > inspect > Console tab and see what's there?

Thank you very much for helping to test this!

**Comment by Joecascio2000** [comment] 2020-07-17 15:00
> That "dexie" warning is really not an issue, just a warning. It won't stop anything from working.
> It's normal that it wasn't able to load the user because you weren't signed in yet.
> 
> Could you please try going in http://testsjoaomgcd.appspot.com/ and the force-refreshing (Ctrl+F5) and see if that forces it to register itself as a device?
> If that doesn't work could you please right-click the page > inspect > Console tab and see what's there?
> 
> Thank you very much for helping to test this!

A force refresh didn't work. Here is the console.
![image](https://user-images.githubusercontent.com/2560796/87800677-8b8dbb00-c803-11ea-94b8-e698b30966bf.png)

**Comment by joaomgcd** [comment] 2020-07-17 15:38
Interesting. Seems like your browser isn't able to register itself on Google's FCM for some reason. Do you know if you maybe disabled web push support in your build by any chance?

**Comment by Joecascio2000** [comment] 2020-07-17 16:41
> Interesting. Seems like your browser isn't able to register itself on Google's FCM for some reason. Do you know if you maybe disabled web push support in your build by any chance?

Bingo. I got it. I disabled browser notifications because they be bugging me. So, browser notifications needs to be enabled and you need to allow join.
![image](https://user-images.githubusercontent.com/2560796/87810201-77e95100-c811-11ea-8214-a7c714bd37c5.png)
![image](https://user-images.githubusercontent.com/2560796/87810278-964f4c80-c811-11ea-8d6e-8381159541d4.png)

**Comment by joaomgcd** [comment] 2020-07-17 16:55
Nice! :) So it's working correctly for you now?

**Comment by Joecascio2000** [comment] 2020-07-17 17:29
> Nice! :) So it's working correctly for you now?

Yup, it's connected. Still testing/configuring notifications. If I run into an issue there, I'll open a different issue thread.

**Comment by joaomgcd** [comment] 2020-07-20 07:43
Cool. I'll close this then. If anyone still has this issue please do let me know and I can re-open it again.

**Closed by joaomgcd** 2020-07-20 07:43 UTC

**Comment by spidy2356** [comment] 2023-10-20 12:23
@joaomgcd i face the same issue like @Itay-kun (https://github.com/joaomgcd/JoinDesktop/issues/1#issuecomment-659651347) , turn on notificaton but still same, can't login on my PC app.

**Comment by n3me5is-git** [comment] 2023-10-21 18:12
> @joaomgcd i face the same issue like @Itay-kun ([#1 (comment)](https://github.com/joaomgcd/JoinDesktop/issues/1#issuecomment-659651347)) , turn on notificaton but still same, can't login on my PC app using brave as default browser. edit: after enable notification, pop ups and redirects , I successfully make my browser as join device. now I get this error "Error! Couldn't connect. Make sure that the app is listening on the port you configure here."

Same here

**Comment by roadbike831** [comment] 2024-01-20 13:32
Hello, how can this be CLOSED?? when it's still a BUG in 2024??? come on 

I downloaded the Join Desktop app and try and load it, get the error "Can't Connect To The Internet" < this 
was a Bug never fixed back in like 2018???? any help?

IF not, no problem. I have other computers I can use Join Desktop App On.

**Comment by robturner45** [comment] 2025-12-29 04:03
lol this never being fixed then?

**Comment by profucius** [comment] 2025-12-29 08:05
Personally I've moved on to Macrodroid, which I find to be a superior automation app.

**Comment by EnigmaSolved** [comment] 2026-01-01 21:52
I'm having the same issue, sadly.
